channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=24.0
- pip:
  - mlflow==2.13.0
  - cloudpickle==2.2.0
  - lz4==3.1.3
  - numpy==1.23.4
  - packaging==23.0
  - psutil==5.9.3
  - pyyaml==5.4.1
  - scikit-learn==1.1.3
  - scipy==1.9.3
name: mlflow-env
